print("Đây là nhập chuỗi bình thường: ")
s = input()
print('s = ',s)
print('\nĐây là nhập theo kiểu int: ')
s = int(input())
print("s = ",s)
print('\nĐây là nhập theo boolean: ')
s= input()
s = s.lower() in ('yes','true','t','1')
print("s = ",s)